### ISSUE TITLE
Ajout d'une nouvelle image image_stand_rse_01

### ISSUE THREAD

**Issue by benl86** [MAM84/StandRSE#1]
Cc,
- Ajout d'une nouvelle image image_stand_rse_01
- Découpe 3*3
- nouvelle page dédiée

![image_stand_rse_01](https://github.com/MAM84/StandRSE/assets/17223642/2ae3ee2b-65bb-47f0-987e-1879f36685ca)

**Comment by MAM84** [comment]
merci !

**Comment by benl86** [comment]
Désolé, je voulais te pousser une branche mais je n'avais pas les droits attendus, d'où ce ticket 😅.

**Comment by MAM84** [comment]
ah zut !!!! t'aurais dû me le dire
je croyais que tu m'avais fait une liste de ce que l'on devait modifier 😅
du coup j'ai travaillé dessus ce soir, j'ai refaire des trucs que tu avais certainement fait alors.....
tant pis !
faudrait quand même qu'on puisse tester sur un écran similaire pour voir le rendu, j'ai des doutes ! je t'en parlerais de vive voix ça sera plus simple que par message
